### PR TITLE
cpp webserver restbed with test suite 

### PR DESCRIPTION
**Pull request by praenubilus**
Add open source [C++ Web Server Restbed](https://github.com/Corvusoft/restbed). Mystikos will crash because of not implemented system calls  `SYS_eventfd2` (https://github.com/deislabs/mystikos/issues/142) and `SYS_faccessat` (https://github.com/deislabs/mystikos/issues/144)

Note: another REST sdk, microsoft/cpprestsdk is also blocked by these two issues https://github.com/microsoft/cpprestsdk

Updates:
---
All syscall blocking issue have been solved.
In all 115 test suites(around 1000 test cases), only one test suite failed. Failure can be reproduced through `run-single-test` or `gdb` recipe.
https://github.com/Corvusoft/restbed/blob/55009b43618c2d3a0e2afad5fd845eddd964816b/test/feature/source/signal_handling/feature.cpp#L65

Blocked by #394

### CODE REVIEW

**Comment by paulcallen** [comment]
eventfd has been fixed. Can you look to see if this works now.

**Comment by jxyang** [comment]
I am investigating the signal assertion failure to see if there is a quick fix.

**Comment by jxyang** [comment]
Identified the root cause as: https://github.com/deislabs/mystikos/issues/394.

I should have a fix soon.

**Comment by jxyang** [comment]
A careful review of the license of cpp restbed shows it might be inappropriate to be included in Mystikos:

> Using the AGPL requires that your work based on the Software must be  licensed under the AGPL. If you wish to develop a work based on the Software but desire to license it under your own terms, e.g. a closed source license, you MUST purchase a Corvusoft Permissive License.

I suggest we close this PR. Instead we create a test case to cover #394. @praenubilus

**Comment by paulcallen** [comment]
closing as we are unlikely going to use this as a test

**Pull request closed without merging**
