### PR TITLE
Add retry and runtest command to dotnet tests

### PR DESCRIPTION
**Pull request by asvrada**

### CODE REVIEW

**Review by vtikoo — APPROVED** [review]
LGTM. Not necessary as part of this PR, but we should also think of setting Makefile level timeouts to protect against hung tests.

**Review by vtikoo — CHANGES_REQUESTED** [review]
Just realized wrapping with RUNTEST introduces a default timeout of 120 secs. @asvrada will that be enough for all the tests changed here?

**Comment by asvrada** [comment]
> Just realized wrapping with RUNTEST introduces a default timeout of 120 secs. @asvrada will that be enough for all the tests changed here?

Will double check

**Comment by asvrada** [comment]
aspnetcore5 and aspnetcore6 are extremely flaky on my local machine... Random tests would hang and timeout, so I am not adding `$(RUNTEST)` command in this PR

**Review by vtikoo — APPROVED** [review]

**Pull request merged**
